[assembly: System.Reflection.AssemblyProduct("Connection string factory")]
[assembly: System.Reflection.AssemblyCompany("Aleksandr Erygin")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2015 Aleksandr Erygin.")]
[assembly: System.Reflection.AssemblyTrademark("Connection string factory")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("0.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("Compiled By alex")]